### ISSUE TITLE
Soft Lock at Whitney

### ISSUE THREAD

**Issue by XModxGodX** [xCrystal/crystal-randofuser#1]
I got a soft lock when Whitney sends out her Miltank or Milpom in this case. (figures Whitney's Miltank would cause problems) I did edit put the game through the UP randomizer before doing the patch and randofusion but I only randomized the wild Pokemon so they'd all be obtainable.

**Comment by xCrystal** [comment]
Yeah, I'm almost certain the problem is going to be the fact that you used the UPR. It's possible that it also shifted around some other unrelated data, and the randofuser and the modified ROM assume that everything is located in the same place as in the original Crystal. Indeed, I know for a fact that if you had applied the UPR after using the randofuser, it would've been a complete mess because the base patch and randofuser shift and/or remake certain data structures for simplicity, and also as a given of using the disassembly. It's very likely that the universal pokemon randomizer is subject to similar restrictions.

That said I'm not completely ruling out the fact that it could've been a bug, but I've played myself up to the E4 and have not encountered any issue like that. Then again, each run is different so who knows.
